# Generated by Django 4.2.26 on 2025-11-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Спортсмен'), ('coach', 'Тренер'), ('admin', 'Администратор')], max_length=255),
        ),
    ]
