# Generated by Django 4.2.13 on 2025-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('Спортсмен', 'Спортсмен'), ('Тренер', 'Тренер'), ('Администратор', 'Администратор')], max_length=255),
        ),
    ]
