# Generated by Django 4.2.13 on 2026-01-10 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_alter_group_group_name_alter_group_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administrator.coach'),
        ),
    ]
