# Generated by Django 4.2.13 on 2026-01-25 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0004_alter_group_coach_alter_slot_coach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
