# Generated by Django 4.2.13 on 2026-01-25 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0005_alter_group_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_students', to='administrator.group')),
                ('student', models.OneToOneField(limit_choices_to={'role': 'Спортсмен'}, on_delete=django.db.models.deletion.CASCADE, related_name='current_groups', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
