# Generated by Django 4.2.13 on 2026-03-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_scheduleperiod_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
        migrations.AddField(
            model_name='schedule',
            name='weekdays',
            field=models.ManyToManyField(to='administrator.weekday'),
        ),
    ]
