# Generated by Django 4.2.13 on 2026-03-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_weekday_remove_schedule_weekday_schedule_weekdays'),
    ]

    operations = [
        migrations.AddField(
            model_name='weekday',
            name='short_name',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
