# Generated by Django 4.2.13 on 2026-03-28 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0010_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date_start', models.DateTimeField()),
                ('date_end', models.DateTimeField()),
                ('sport_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingtype')),
            ],
            options={
                'unique_together': {('title', 'sport_type', 'date_start', 'date_end')},
            },
        ),
    ]
