# Generated by Django 4.2.13 on 2026-04-04 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0011_competition'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('next_stage', models.CharField(choices=[('НП1', 'НП1'), ('НП2', 'НП2'), ('ТЭ до 1г.', 'ТЭ до 1г.'), ('ТЭ св 1г(1).', 'ТЭ св 1г(1).'), ('ТЭ св 1г(2)', 'ТЭ св 1г(2)'), ('ТЭ св 3-х лет', 'ТЭ св 3-х лет'), ('ТЭ св 3-х лет(2)', 'ТЭ св 3-х лет(2)'), ('ТЭ св 3-х лет(3)', 'ТЭ св 3-х лет(3)'), ('ССМ(1)', 'ССМ(1)'), ('ССМ(2)', 'ССМ(2)'), ('ССМ(3)', 'ССМ(3)'), ('ВСМ', 'ВСМ')], max_length=255)),
                ('is_passed', models.BooleanField(default=False)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('coach', models.ForeignKey(limit_choices_to={'role': 'Тренер'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.group')),
            ],
            options={
                'unique_together': {('name', 'coach', 'group', 'date_start', 'date_end')},
            },
        ),
    ]
