# Generated by Django 4.2.13 on 2026-04-04 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_assessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='sport_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingtype'),
            preserve_default=False,
        ),
    ]
