# Generated by Django 4.2.13 on 2026-04-11 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_testitem_assessmentresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='stage',
            field=models.CharField(choices=[('НП1', 'НП1'), ('НП2', 'НП2'), ('ТЭ до 1г.', 'ТЭ до 1г.'), ('ТЭ св 1г(1).', 'ТЭ св 1г(1).'), ('ТЭ св 1г(2)', 'ТЭ св 1г(2)'), ('ТЭ св 3-х лет', 'ТЭ св 3-х лет'), ('ТЭ св 3-х лет(2)', 'ТЭ св 3-х лет(2)'), ('ТЭ св 3-х лет(3)', 'ТЭ св 3-х лет(3)'), ('ССМ(1)', 'ССМ(1)'), ('ССМ(2)', 'ССМ(2)'), ('ССМ(3)', 'ССМ(3)'), ('ВСМ', 'ВСМ')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
