# Generated by Django 4.2.13 on 2026-04-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_testitem_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testitem',
            old_name='max_cor',
            new_name='max_cor_female',
        ),
        migrations.AddField(
            model_name='testitem',
            name='max_cor_male',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
