# Generated by Django 4.2.13 on 2026-04-11 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0016_rename_max_cor_testitem_max_cor_female_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='max_cor_female',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='testitem',
            name='max_cor_male',
            field=models.FloatField(),
        ),
    ]
