# Generated by Django 4.2.13 on 2026-05-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0017_alter_testitem_max_cor_female_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slots', to='administrator.schedule'),
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('planned', 'Запланирована'), ('completed', 'Проведена'), ('cancelled', 'Отменена')], default='planned', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='student',
            field=models.ForeignKey(limit_choices_to={'role': 'Спортсмен'}, on_delete=django.db.models.deletion.CASCADE, related_name='current_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
