# Generated by Django 4.2.13 on 2026-05-16 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_attendance_arrival_time_attendance_marked_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='administrator.schedule'),
        ),
    ]
