# Generated by Django 4.2.26 on 2026-07-25 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0019_alter_slot_schedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='is_passed',
        ),
    ]
