# Generated by Django 4.2.26 on 2026-07-25 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0020_remove_assessment_is_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='passed',
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='result',
            field=models.CharField(choices=[('passed', 'Сдал'), ('failed', 'Не сдал'), ('absent', 'Отсутствовал'), ('exempted', 'Освобожден')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
