# Generated by Django 4.2.26 on 2026-07-25 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0021_remove_assessmentresult_passed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='assessment_type',
            field=models.CharField(choices=[('general', 'ОФП'), ('speсial', 'СФП')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
