# Generated by Django 4.2.26 on 2026-08-02 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0022_assessment_assessment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
