# Generated by Django 4.2.26 on 2026-08-08 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0023_alter_assessmentresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment',
            name='assessment_type',
        ),
        migrations.AddField(
            model_name='testitem',
            name='assessment_type',
            field=models.CharField(choices=[('general', 'ОФП'), ('speсial', 'СФП')], default=1, max_length=50),
            preserve_default=False,
        ),
    ]
