# Generated by Django 4.2.26 on 2026-08-08 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0024_remove_assessment_assessment_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='sport_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administrator.trainingtype'),
            preserve_default=False,
        ),
    ]
