# Generated by Django 4.2.26 on 2026-08-09 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0025_testitem_sport_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='unit',
            field=models.CharField(choices=[('seconds', 'сек.'), ('minutes', 'мин.'), ('centimeters', 'см.'), ('meters', 'м.'), ('quantity', 'кол-во.повт.')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
