# Generated by Django 4.2.26 on 2026-08-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0026_testitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testitem',
            name='unit',
            field=models.CharField(choices=[('секунды', 'сек.'), ('минуты', 'мин.'), ('сантиметры', 'см.'), ('метры', 'м.'), ('количество повторений', 'кол-во.повт.')], max_length=255),
        ),
    ]
