# Generated by Django 4.2.26 on 2026-09-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0028_alter_assessmentresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='max_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testitem',
            name='min_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
