# Generated by Django 4.2.26 on 2026-09-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0029_testitem_max_value_testitem_min_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='better_direction',
            field=models.CharField(choices=[('lower', 'меньше-лучше'), ('higher', 'больше-лучше')], default='lower', max_length=10),
        ),
    ]
